// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-bIBJ4LEFt0v8ZT1fW_Sm2JkMYMSiy5E',
    appId: '1:513935140062:web:863d7d375c6fdddf194e4f',
    messagingSenderId: '513935140062',
    projectId: 'tourguideom-2861a',
    authDomain: 'tourguideom-2861a.firebaseapp.com',
    storageBucket: 'tourguideom-2861a.appspot.com',
    measurementId: 'G-EVKY5F25VR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV-M2KkCQC7aKm9WziZrayv0twaQo8-U8',
    appId: '1:513935140062:android:96c9e128b7d479aa194e4f',
    messagingSenderId: '513935140062',
    projectId: 'tourguideom-2861a',
    storageBucket: 'tourguideom-2861a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGSUXIVnB3-rGHGyMsbm0iYJzUvdnOQCo',
    appId: '1:513935140062:ios:b3d6ff4995964a15194e4f',
    messagingSenderId: '513935140062',
    projectId: 'tourguideom-2861a',
    storageBucket: 'tourguideom-2861a.appspot.com',
    iosClientId: '513935140062-s7mdteh623kjqc4jbo98hn327jhl2d6u.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGSUXIVnB3-rGHGyMsbm0iYJzUvdnOQCo',
    appId: '1:513935140062:ios:b3d6ff4995964a15194e4f',
    messagingSenderId: '513935140062',
    projectId: 'tourguideom-2861a',
    storageBucket: 'tourguideom-2861a.appspot.com',
    iosClientId: '513935140062-s7mdteh623kjqc4jbo98hn327jhl2d6u.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );
}
